apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app1
  labels:
    app:  nodejs-app1
spec:
  replicas: 3
  selector:
    matchLabels:
      app:  nodejs-app1
  template:
    metadata:
      labels:
        app:  nodejs-app1
    spec:
      containers:
      - name:  nodejs-app1
        image: nginx:1.14.2
        ports:
        - containerPort: 3000